import Foundation

struct VCDSignal: Identifiable {
    let id = UUID()
    let name: String
    let symbol: String
    let isBus: Bool
    var timeline: [TimePoint]
}

struct TimePoint {
    let time: Int
    let value: String // (e.g., "b0001" or "1")
}

class VerilogCore {
    private let iverilogPath = "/opt/homebrew/bin/iverilog"
    private let vvpPath = "/opt/homebrew/bin/vvp"
    
    func runSimulation(sourceCode: String, directory: URL) -> String {
        let designURL = directory.appendingPathComponent("design.v")
        let outputVVPURL = directory.appendingPathComponent("sim.vvp")
        
        // --- 1. SAVE THE SOURCE CODE TO DISK FIRST ---
        do {
            try sourceCode.write(to: designURL, atomically: true, encoding: .utf8)
        } catch {
            return "❌ Error: Failed to write design file to disk.\n"
        }
        
        // --- 2. DYNAMIC PARSER: Parse the sourceCode string directly from memory ---
        var dynamicVCDName = "wave.vcd" // Default safe fallback
        
        // Regex pattern to capture: $dumpfile("filename.vcd");
        let pattern = #"\$dumpfile\s*\(\s*"([^"]+)"\s*\)"#
        if let regex = try? NSRegularExpression(pattern: pattern, options: []),
           let match = regex.firstMatch(in: sourceCode, options: [], range: NSRange(sourceCode.startIndex..., in: sourceCode)) {
            
            // Extract the string inside the quotes (Capture Group 1)
            if let outputRange = Range(match.range(at: 1), in: sourceCode) {
                dynamicVCDName = String(sourceCode[outputRange])
                print("💡 MacVerilog dynamically detected output filename: \(dynamicVCDName)")
            }
        }
        
        let outputVCDURL = directory.appendingPathComponent(dynamicVCDName)
        
        // Remove stale VCD files to prevent false-positives on error
        try? FileManager.default.removeItem(at: outputVCDURL)
        
        // --- 3. SUBPROCESS CONFIGURATION AND EXECUTION ---
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.currentDirectoryURL = directory
        
        let shellCommand = """
        export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
        iverilog -o "\(outputVVPURL.path)" "\(designURL.path)" && vvp "\(outputVVPURL.path)" -vcd "\(outputVCDURL.path)"
        """
        process.arguments = ["-c", shellCommand]
        
        let errorPipe = Pipe()
        process.standardError = errorPipe
        
        do {
            try process.run()
            process.waitUntilExit()
            
            if process.terminationStatus != 0 {
                let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
                return "❌ Syntax Error:\n" + (String(data: errorData, encoding: .utf8) ?? "")
            }
            
            // Verify execution against the newly extracted dynamic file path
            return FileManager.default.fileExists(atPath: outputVCDURL.path) ? "✅ Compiled and simulated OK!\n" : "⚠️ \(dynamicVCDName) missing.\n"
        } catch {
            return "❌ Subprocess Error: \(error.localizedDescription)\n"
        }
    }
    
    func parseVCD(vcdURL: URL) -> [VCDSignal] {
        guard let content = try? String(contentsOf: vcdURL, encoding: .utf8) else { return [] }
        var signals: [VCDSignal] = []
        var currentTime = 0
        let lines = content.components(separatedBy: .newlines)
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.isEmpty { continue }
            
            // Matches: $var reg 4 ! count [3:0] $end OR $var wire 1 # clk $end
            if trimmed.hasPrefix("$var") {
                let parts = trimmed.components(separatedBy: .whitespaces).filter { !$0.isEmpty }
                if parts.count >= 5 {
                    let size = parts[2]
                    let symbol = parts[3]
                    let name = parts[4]
                    
                    // Prevent duplicate signal definitions generated by Icarus Verilog
                    if !signals.contains(where: { $0.name == name }) {
                        signals.append(VCDSignal(name: name, symbol: symbol, isBus: size != "1", timeline: []))
                    }
                }
            } else if trimmed.hasPrefix("#") {
                if let timeInt = Int(trimmed.dropFirst()) {
                    currentTime = timeInt
                }
            }
            // Parse Multi-bit Bus values (e.g., b0001 !)
            else if trimmed.hasPrefix("b") {
                let parts = trimmed.dropFirst().components(separatedBy: .whitespaces).filter { !$0.isEmpty }
                if parts.count == 2 {
                    let val = parts[0]
                    let symbol = parts[1]
                    if let idx = signals.firstIndex(where: { $0.symbol == symbol }) {
                        signals[idx].timeline.append(TimePoint(time: currentTime, value: val))
                    }
                }
            }
            // Parse Single-bit Wire values (e.g., 1# or 0#)
            else if trimmed.count >= 2 && (trimmed.hasPrefix("0") || trimmed.hasPrefix("1")) {
                let val = String(trimmed.prefix(1))
                let symbol = String(trimmed.dropFirst())
                if let idx = signals.firstIndex(where: { $0.symbol == symbol }) {
                    signals[idx].timeline.append(TimePoint(time: currentTime, value: val))
                }
            }
        }
        return signals
    }
    
    func runMultiFileSimulation(projectFiles: [ProjectFile], contentMap: [UUID: String], directory: URL) -> String {
        for file in projectFiles {
            guard let content = contentMap[file.id] else { continue }
            let fileURL = directory.appendingPathComponent(file.name)
            try? content.write(to: fileURL, atomically: true, encoding: .utf8)
        }
        
        let outputVVPURL = directory.appendingPathComponent("sim.vvp")
        
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.currentDirectoryURL = directory
        
        let shellCommand = """
    export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
    iverilog -o "\(outputVVPURL.path)" *.v && vvp "\(outputVVPURL.path)"
    """
        process.arguments = ["-c", shellCommand]
        
        let errorPipe = Pipe()
        process.standardError = errorPipe
        
        do {
            try process.run()
            process.waitUntilExit()
            
            if process.terminationStatus != 0 {
                let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
                return "❌ Syntax Error:\n" + (String(data: errorData, encoding: .utf8) ?? "")
            }
            
            return "✅ Compiled and simulated all project files successfully!\n"
        } catch {
            return "❌ Subprocess Error: \(error.localizedDescription)\n"
        }
    }
}
